name: Run PowerShell Script

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install NuGet Package WinSCP
      run: |
        # Install NuGet if not already installed
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile "$env:TEMP\nuget.exe"
        if (-not (Test-Path "$env:TEMP\nuget.exe")) {
          Write-Host "NuGet CLI installation failed"
          exit 1
        }
        $env:Path += ";$env:TEMP"

        # Install WinSCP NuGet package
        nuget install WinSCP -Source https://www.nuget.org/api/v2 -OutputDirectory "$env:TEMP\WinSCP"

    - name: List Contents of WinSCP Directory
      run: |
        $WinSCPPackagePath = "$env:TEMP\WinSCP"
        Write-Host "Listing contents of WinSCP directory:"
        Get-ChildItem -Path $WinSCPPackagePath -Recurse | ForEach-Object { Write-Host $_.FullName }

    - name: Import WinSCP Assembly and Run Script
      run: |
        # Dynamically find the correct path for WinSCP .NET assembly
        $WinSCPAssemblyPath = Get-ChildItem -Path "$env:TEMP\WinSCP" -Recurse -Filter 'WinSCPnet.dll' | Select-Object -First 1

        if ($WinSCPAssemblyPath) {
          Write-Host "Found WinSCP .NET Assembly at: $($WinSCPAssemblyPath.FullName)"
          try {
              Add-Type -Path $WinSCPAssemblyPath.FullName
              Write-Host "WinSCP .NET Assembly loaded successfully."
          } catch {
              Write-Host "Error loading WinSCP .NET Assembly: $_"
              exit 1
          }

          # Set FTP-related secrets as environment variables
          $env:FTP_USER = "${{ secrets.FTP_USER }}"
          $env:PREPRODFTPKEY = "${{ secrets.PREPRODFTPKEY }}"
          $env:SSH_HOST_KEY_FINGERPRINT = "${{ secrets.SSH_HOST_KEY_FINGERPRINT }}"

          # Ensure clientmongo.ps1 exists before running it
          if (-not (Test-Path "./clientmongo.ps1")) {
              Write-Host "clientmongo.ps1 script not found."
              exit 1
          }

          # Run the PowerShell script using WinSCP
          pwsh -File ./clientmongo.ps1
        } else {
          Write-Host "WinSCP .NET Assembly not found."
          exit 1
        }
