name: Test SSH Connection to FTP Server

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test-connection:
    runs-on: windows-latest  # Running on Windows

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Prepare SSH private key
      run: |
        # Fetch the private key from GitHub Secrets and save it to a file
        echo "${{ secrets.FTP_PRIVATE_KEY }}" > pri.key
        
    - name: Set permissions for the private key
      run: |
        chmod 600 pri.key

    - name: Set FTP user environment variable
      run: |
        echo "FTP_USER=${{ secrets.FTP_USER }}" >> $GITHUB_ENV

    - name: Execute PowerShell script
      run: |
        pwsh -File ./clientmongo.ps1
