name: FTP/SFTP Upload or Download

on:
  push:
    branches:
      - test

jobs:
  ftp_job:
    runs-on: windows-latest  # or ubuntu-latest if you use Linux

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PowerShell environment and run FTP connection script
      run: |
        # Write the FTP_PRIVATE_KEY secret to a file
        $env:FTP_PRIVATE_KEY = "${{ secrets.FTP_PRIVATE_KEY }}"
        $env:FTP_USER = "${{ secrets.FTP_USER }}"
        $env:FTP_SERVER_HOST = "preprodftp.windsoft.ro"  # Replace with your FTP server host

        # Run PowerShell script
        pwsh -File ./clientmongo.ps1 -FTPUser $env:FTP_USER -FTPPrivateKey $env:FTP_PRIVATE_KEY -FTPServerHost $env:FTP_SERVER_HOST
