name: Test SSH Connection to FTP Server

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test-connection:
    runs-on: windows-latest  # Running on Windows

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Prepare SSH private key
      run: |
        # Fetch the private key from GitHub Secrets
        echo "${{ secrets.FTP_PRIVATE_KEY }}" > pri.key
        
        # Reformat the private key to ensure proper newlines
        sed 's/ \\n /\n/g' pri.key > formatted_pri.key
        mv formatted_pri.key pri.key

        # Verify the key by checking its validity
        ssh-keygen -y -f pri.key || { echo "Invalid private key"; exit 1; }

        # Set permissions on the private key (this step is more Linux-focused)
        chmod 600 pri.key

    - name: Test SSH connection to FTP server
      run: |
        # Test the SSH connection to the FTP server using the private key
        echo "Testing SSH connection to FTP server..."
        ssh -o StrictHostKeyChecking=no -i pri.key preprodftp@92.180.12.186 ls
      shell: bash
