name: Connect to FTP Server

on:
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Connect to FTP Server
        env:
          FTP_SERVER: "sftp://preprodftp.windsoft.ro/F4F"
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PRIVATE_KEY: ${{ secrets.FTP_PRIVATE_KEY }}
        run: |
          # Save the PEM key to a file
          echo "$FTP_PRIVATE_KEY" > pri.key
          
          # Set permissions
          cmd /c "icacls pri.key /inheritance:r /grant:r $env:USERNAME:(R)"
          
          # Test the SSH connection
          ssh -o StrictHostKeyChecking=no -i pri.key $FTP_USER@preprodftp.windsoft.ro ls
        shell: bash
