name: MongoDB Export/Import

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the 'test' branch


jobs:
  mongo-export-import:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MongoDB Export and Import Script
        env:
          PREPRODURI: ${{ secrets.PREPRODURI }}  # MongoDB preprod URI from secrets
          PRODURI: ${{ secrets.PRODURI }}        # MongoDB prod URI from secrets
        run: |
          # Debug the MongoDB URIs
          Write-Host "PREPRODURI: $env:PREPRODURI"
          Write-Host "PRODURI: $env:PRODURI"

          # Ensure the MongoDB tools path is correctly added to the PowerShell session
          $env:PATH = "C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin;" + $env:PATH
          Write-Host "Current PATH: $env:PATH"

          # Verify that mongoexport.exe is recognized by PowerShell
          Get-Command -Name "C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin\mongoexport.exe"

          # Define collections to export and import
          $collections = @("Client", "User")

          foreach ($collectionName in $collections) {
            # Set export paths
            $exportPath = "C:\exported_data\$collectionName.json"

            # Step 4: Export collection data from preprod to a file
            Write-Host "Exporting $collectionName data from preprod"
            & 'C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin\mongoexport.exe' --uri=$env:PREPRODURI --db=SyncNotifyHubService --collection=$collectionName --out=$exportPath --jsonArray
            Write-Host "Exported $collectionName data to $exportPath"

            # Step 5: Import collection data into prod
            Write-Host "Importing $collectionName data into prod"
            & 'C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin\mongoimport.exe' --uri=$env:PRODURI --db=SyncNotifyHubService --collection=$collectionName --file=$exportPath --jsonArray --upsert --verbose 
            Write-Host "Imported $collectionName data into prod"
