name: MongoDB Export and Import

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the main branch

jobs:
  mongo-export-import:
    runs-on: windows-latest  # Use Windows runner for PowerShell

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up PowerShell
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    # Step 3: Install MongoDB Tools
    - name: Install MongoDB Tools
      run: |
        choco install mongodb-tools

    # Step 4: Set up environment variables for MongoDB credentials
    - name: Set up MongoDB credentials
      env:
        PREPRODURI: ${{ secrets.PREPRODURI }}
        PRODURI: ${{ secrets.PRODURI }}
      run: |
        # Run the PowerShell script, passing the export path
        pwsh -Command |
          . ${{ github.workspace }}\scripts\export-import.ps1 -exportPath "$env:GITHUB_WORKSPACE\$collectionName.json"
