name: MongoDB Export and Import

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the 'test' branch

jobs:
  mongo-export-import:
    runs-on: windows-latest  # Use Windows runner for PowerShell

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install MongoDB Tools
      run: |
        Invoke-WebRequest -Uri "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-100.5.1.zip" -OutFile "mongodb-tools.zip"
        Expand-Archive -Path "mongodb-tools.zip" -DestinationPath "C:\mongodb-tools"
        $env:PATH += ";C:\mongodb-tools\bin"
    
    # Step 2: Set up MongoDB credentials
    - name: Set up MongoDB credentials
      env:
        PREPRODURI: ${{ secrets.PREPRODURI }}
        PRODURI: ${{ secrets.PRODURI }}
      run: |
        # Run the PowerShell script, passing the export path
        pwsh -Command "& .\mongo.ps1 -exportPath \"$env:GITHUB_WORKSPACE\$collectionName.json\""
