name: MongoDB Export and Import

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the 'test' branch

jobs:
  mongo-export-import:
    runs-on: windows-latest  # Use Windows runner for PowerShell

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Download and install MongoDB Tools
    - name: Install MongoDB Tools
      run: |
        # Download and extract MongoDB tools
        Invoke-WebRequest -Uri "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-100.5.1.zip" -OutFile "mongodb-tools.zip"
        Expand-Archive -Path "mongodb-tools.zip" -DestinationPath "C:\mongodb-tools"
        
        # Check if the tools are extracted correctly
        Write-Host "Verifying mongoexport installation"
        Get-Command mongoexport || Write-Host "mongoexport not found in path"
        
        # Add MongoDB tools to the PATH environment variable
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\mongodb-tools\bin", "Machine")

        # Verify if mongoexport is now accessible
        Write-Host "Verifying mongoexport after PATH update"
        Get-Command mongoexport || Write-Host "mongoexport still not found"

    # Step 3: Set up MongoDB credentials and export/import the data
    - name: Run MongoDB Export and Import Script
      env:
        PREPRODURI: ${{ secrets.PREPRODURI }}  # MongoDB preprod URI from secrets
        PRODURI: ${{ secrets.PRODURI }}        # MongoDB prod URI from secrets
      run: |
        # Ensure mongo.ps1 is in the root directory of the repository
        $exportPath = "$env:GITHUB_WORKSPACE\$($env:COLLECTION_NAME).json"
        pwsh -Command "& .\mongo.ps1 -exportPath '$exportPath'"
