name: MongoDB Export and Import

on:
  push:
    branches:
      - test  # Trigger the workflow on push to the 'test' branch

jobs:
  mongo-export-import:
    runs-on: windows-latest  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Download and install MongoDB Tools
    - name: Install MongoDB Tools
      run: |
        # Download MongoDB tools and unzip them
        Invoke-WebRequest -Uri "https://fastdl.mongodb.org/tools/db/mongodb-database-tools-windows-x86_64-100.10.0.zip" -OutFile "mongodb-tools.zip"
        Expand-Archive -Path "mongodb-tools.zip" -DestinationPath "C:\mongodb-tools"

        # Debugging step to list contents of the extracted folder
        Write-Host "Listing files in the extracted MongoDB tools folder:"
        Get-ChildItem -Path "C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin" -Recurse

        # Add MongoDB tools to PATH and persist across steps
        echo "C:\mongodb-tools\mongodb-database-tools-windows-x86_64-100.10.0\bin" >> $GITHUB_ENV  
    - name: github secrets
      env: 
        PREPROD_USERNAME: ${{secrets.PREPROD_USERNAME}}
        PREPROD_PASSWORD: ${{secrets.PREPROD_PASSWORD}}

    # Step 3: Run PowerShell Script
    - name: Run PowerShell Script
      run: |
        # Call the PowerShell script
        .\mongo.ps1
